// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxcPowhYI1QGecFCR_4ztEIr6QeauSB3Y',
    appId: '1:489357901677:web:d817f2d1df2ccea68a6464',
    messagingSenderId: '489357901677',
    projectId: 'spendwise-ef296',
    authDomain: 'spendwise-ef296.firebaseapp.com',
    storageBucket: 'spendwise-ef296.firebasestorage.app',
    measurementId: 'G-NNS4B8WHGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXx9DIVTvm0I_0tZ6WWFDlsMFz4uQNcog',
    appId: '1:489357901677:android:30086d761bf229c18a6464',
    messagingSenderId: '489357901677',
    projectId: 'spendwise-ef296',
    storageBucket: 'spendwise-ef296.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDJflYayM8onhJFPHP3zUCP4s9lvEEUec',
    appId: '1:489357901677:ios:9fec236913779e138a6464',
    messagingSenderId: '489357901677',
    projectId: 'spendwise-ef296',
    storageBucket: 'spendwise-ef296.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDJflYayM8onhJFPHP3zUCP4s9lvEEUec',
    appId: '1:489357901677:ios:9fec236913779e138a6464',
    messagingSenderId: '489357901677',
    projectId: 'spendwise-ef296',
    storageBucket: 'spendwise-ef296.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxcPowhYI1QGecFCR_4ztEIr6QeauSB3Y',
    appId: '1:489357901677:web:a43595ef1f7e4e118a6464',
    messagingSenderId: '489357901677',
    projectId: 'spendwise-ef296',
    authDomain: 'spendwise-ef296.firebaseapp.com',
    storageBucket: 'spendwise-ef296.firebasestorage.app',
    measurementId: 'G-X0MMSRGZN8',
  );
}
